local o = vim.o
o.cursorlineopt = "both"
o.tabstop = 8
o.softtabstop = 4
o.shiftwidth = 4
o.number = true
o.relativenumber = true
o.smartindent = true
o.smarttab = true
o.autoindent = true
o.expandtab = true
o.undofile = true
o.colorcolumn = "80"
o.clipboard = "unnamedplus"
o.termguicolors = true
o.mousemoveevent = true
