[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
family = "FiraMono Nerd Font"
style = "Medium"

[general]
import = ["/home/denzel/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.65
blur = true
decorations = "None"

[window.dimensions]
columns = 106
lines = 31
