[cursor.style]
blinking = "On"

[font]
size = 12.75

[font.normal]
family = "IosevkaTerm Nerd Font"
# family = "JetbrainsMono Nerd Font"
# family = "GohuFont 11 Nerd Font Mono"
style = "Regular"

[general]
import = ["/home/denzel/.config/alacritty/themes/themes/tokyo_night.toml"]

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/tmux"

[window]
# blur = true
decorations = "None"
dynamic_padding = true
# dynamic_title = false
# opacity = 0.75
# title = "Terminal - Alacritty"

[window.dimensions]
columns = 106
lines = 31

[env]
TERM = "xterm-256color"
