[cursor.style]
blinking = "On"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = ["/home/denzel/.config/alacritty/themes/themes/tokyo_night_storm.toml"]

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
blur = true
decorations = "None"
dynamic_padding = true
# dynamic_title = false
opacity = 0.75
# title = "Terminal - Alacritty"

[window.dimensions]
columns = 106
lines = 31

[window.padding]
x = 0
y = 0
