[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12.75

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[general]
import = ["/home/denzel/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.65
blur = true
decorations = "None"

[window.dimensions]
columns = 106
lines = 31

[window.padding]
x = 2
y = 2
