[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Jetbrains mono Nerd Font"
style = "Regular"

[general]
import = ["/home/denzel/.config/alacritty/themes/themes/tokyonight_moon.toml"]

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "None"
dynamic_padding = true

[window.dimensions]
columns = 106
lines = 31
